on: push
name: Libris - Generate Documentation
jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version to use

      # Install dependencies.
      - name: Install Dependencies
        # run: npm ci
        run: npm install @librisio/libris
      
      - name: Libris - Generate Documentation
        uses: librisio/libris-auto-gen@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LIBRIS_API_KEY: ${{ secrets.LIBRIS_API_KEY }}
        with:
          config: './docs/config.js'
          output: './docs/index.html'
