# Libris Auto-Generate Documenation Action.
#   Seamlessly integrate Libris with your development workflow to guarantee your documentation remains up-to-date.
#   Our action automates the generation of documentation each time you push to your repository, ensuring accuracy and consistency without manual effort.

name: Libris - Generate Documentation

# Grant write permissions in order to write the generated documentation file to your repo.
permissions:
  contents: write

# Trigger on every push.
on: push

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Optionally install Node.js and dependencies.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        # run: npm ci
        run: npm install @librisio/libris
      
      # Generate documentation.
      - name: Libris - Generate Documentation
        uses: librisio/libris-action@main
        env:

          # Your secret github token.
          # This token is automatically generated by github.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 

          # Your Libris API Key.
          # Must manually be created under "Settings > Secrets and variables > Actions > New repository secret".
          LIBRIS_API_KEY: ${{ secrets.LIBRIS_API_KEY }}

        with:

          # The relative input path of your configuration file, may either be a JSON or JavaScript file.
          config: './docs/config.js'

          # The relative output path for the generated documentation file.
          output: './docs/index.html'

          # The branch to where the newly generated documentation file will be pushed to.
          # Leave "" to use the branch that is being pushed.
          branch: 'docs'

          # Create an orphan branch when the defined branch does not exist.
          orphan: 'true'
          